/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SourcesIdRouteImport } from './routes/sources.$id'
import { Route as SourcesNewRouteImport } from './routes/sources.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpportunitiesRoute,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIdRoute = SourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNewRoute = SourcesNewRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/packs': typeof PacksRoute
  '/triage': typeof TriageRoute
  '/api/health': typeof ApiHealthRoute
  '/items/$id': typeof ItemsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/sources/new': typeof SourcesNewRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/packs': typeof PacksRoute
  '/triage': typeof TriageRoute
  '/api/health': typeof ApiHealthRoute
  '/items/$id': typeof ItemsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/sources/new': typeof SourcesNewRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/sources': typeof SourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/packs': typeof PacksRoute
  '/triage': typeof TriageRoute
  '/api/health': typeof ApiHealthRoute
  '/items/$id': typeof ItemsIdRoute
  '/sources/$id': typeof SourcesIdRoute
  '/sources/new': typeof SourcesNewRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/opportunities'
    | '/packs'
    | '/triage'
    | '/api/health'
    | '/items/$id'
    | '/sources/$id'
    | '/sources/new'
    | '/opportunities/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/packs'
    | '/triage'
    | '/api/health'
    | '/items/$id'
    | '/sources/$id'
    | '/sources/new'
    | '/opportunities'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/opportunities'
    | '/packs'
    | '/triage'
    | '/api/health'
    | '/items/$id'
    | '/sources/$id'
    | '/sources/new'
    | '/opportunities/'
    | '/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  PacksRoute: typeof PacksRoute
  TriageRoute: typeof TriageRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ItemsIdRoute: typeof ItemsIdRoute
  SourcesIdRoute: typeof SourcesIdRoute
  SourcesNewRoute: typeof SourcesNewRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$id': {
      id: '/sources/$id'
      path: '/sources/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof SourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/new': {
      id: '/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof SourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  PacksRoute: PacksRoute,
  TriageRoute: TriageRoute,
  ApiHealthRoute: ApiHealthRoute,
  ItemsIdRoute: ItemsIdRoute,
  SourcesIdRoute: SourcesIdRoute,
  SourcesNewRoute: SourcesNewRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
